# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Xet93yoLhu4kP9ZCy940-XSRIMEleFX
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Estadistica").getOrCreate()

spark.stop()

spark

from google.colab import files

csv = spark.read.csv("/content/inventario de tecnologia .csv", )

csv.show()

import pandas as pd

data ={'Producto': ['Laptop','Tableb','Smartphone','Monitor','Teclado',' Ratón','Auriculares','Camara web','Impresora','Disco Duro Externo'],
       'Precio':[1200,500,1000,800,100,100,100,700,900,200],
       'Cantidad en stock':[25,50,10,30,150,200,75,40,20,60],
       'Calificacion (1-5)':[4.5,4.2,4.8,4.3,4.1,3.9,4.4,4,3.8,4.6]
}
df = pd.DataFrame(data)

variable.select(mean(col("Precio")).alias("Media")).show()